### ISSUE TITLE
Przygotować diagramy UML

### ISSUE THREAD

**Issue by karoljanic** [karoljanic/DataStreamAnalyticsApp#12]
Diagram aktywności
Diagram sekwencyjny

**Comment by gamsus** [comment]
![Image](https://github.com/karoljanic/DataStreamAnalyticsApp/assets/92788796/3f7c26ac-3031-4b97-b082-013bfea0f106)

Zacząłem coś tam z wykresami tu daje link jakby ktoś widział jakieś poprawki to daje tu .drawio jest na discordzie.
