### ISSUE TITLE
Zaznajomić się z pythonowymi bibliotekami służącymi do screapowania stron internetowych

### ISSUE THREAD

**Issue by karoljanic** [karoljanic/DataStreamAnalyticsApp#7]
https://www.python.org/
https://scrapy.org/
https://selenium-python.readthedocs.io/

**Comment by MrKubul** [comment]
Beautiful Soup4 do parsowania scrapowanego tekstu

**Comment by Grubre** [comment]
Do samego scrapowania patrzyłem na https://scrapy.org/
